unit_Avto/bitlyapp/urls.py
from django.urls import path
from .views import AccordanceApiView, AccordanceRedirect, AccordanceCreateView, AccordanceListView, \
    AccordanceListApiView

app_name = "bitlyapp"

urlpatterns = [
    path('', AccordanceApiView.as_view(), name='accordance'),
    path('api-list/', AccordanceListApiView.as_view(), name='accordance-api-list'),
    path('create/', AccordanceCreateView.as_view(), name='accordance-create'),
    path('list/', AccordanceListView.as_view(), name='accordance-list'),
    path('<str:short_url>/', AccordanceRedirect.as_view(), name='accordance-redirect'),
]

unit_Avto/unit_Avto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bitlyapp.urls')),
]

unit_Avto/bitlyapp/models.py
from django.db import models

class Accordance(models.Model):
    """
    Модель соответствия полной ссылки - короткой ссылке
    """
    class Meta:
        ordering = ["pk"]
    full_url = models.CharField(blank=False, null=False, max_length=300)  # полная ссылка
    short_url = models.CharField(blank=True, null=True, max_length=150)  # сокращенная ссылка

unit_Avto/bitlyapp/forms.py
from django import forms
from bitlyapp.models import Accordance


class AccordanceForm(forms.ModelForm):
    """
    Форма создание короткой ссылки с возможностью задать кастомную ссылку
    """
    custom_url = forms.CharField(label='Custom url (optional)', help_text="Example: mysuperurl", max_length=100, required=False)

    class Meta:
        model = Accordance
        fields = ['full_url', 'custom_url']
        widgets = {
            'full_url': forms.URLInput(attrs={'initial': 'https://', 'max_length': 300, 'class': 'wide-input'}),
        }
        error_messages = {
            'full_url': {'required': 'Please enter your full url'},
        }


    def clean_full_url(self):
        full_url = self.cleaned_data.get('full_url')

        # проверка на существование сокращения полной ссылки
        if Accordance.objects.filter(full_url=full_url).exists():
            raise forms.ValidationError("There is already a short link for this URL")

        # Проверка доступности URL
        import requests
        try:
            response = requests.get(full_url)
            if response.status_code != 200:
                raise forms.ValidationError("The URL is not available.")
        except requests.RequestException:
            raise forms.ValidationError("The URL is not available.")

        return full_url

unit_Avto/bitlyapp/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework import status
from django import forms
from .forms import AccordanceForm
from .models import Accordance
from .serializers import AccordanceSerializer
from django.views.generic.base import RedirectView


class AccordanceApiView(APIView):
    """
    Метод POST предоставляет короткую ссылку
    Пример запроса:
    POST {"full_url": "https://www.google.com"}
    Также метод POST предоставляет возможность создания кастомной ссылки, для этого необходимо добавить параметр "custom_url"
    Пример запроса на создание кастомной ссылки:
    POST {"full_url": "https://docs.python.org/3/library/datetime.html", "custom_url": "mycustomurl"}
    """

    def post(self, request: Request) -> Response:
        """
        Метод предоставления короткой ссылки и сохранение ее соответствия в базе данных
        """
        serializer = AccordanceSerializer(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class AccordanceListApiView(ListAPIView):
    """
    Метод GET предоставляет список доступных коротких ссылок
    """
    queryset = Accordance.objects.all()
    serializer_class = AccordanceSerializer


class AccordanceCreateView(CreateView):
    """
    Создание короткой ссылки
    """
    model = Accordance
    form_class = AccordanceForm
    template_name = "bitlyapp/accordance_form.html"
    success_url = reverse_lazy('bitlyapp:accordance-list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        custom_url = self.request.POST.get('custom_url', None)
        if custom_url:
            if Accordance.objects.filter(short_url=f"http://127.0.0.1:8000/{custom_url}/").exists():
                form.add_error('custom_url', forms.ValidationError("There is already a short link for this URL"))
                return self.form_invalid(form)
            else:
                short_url = f"http://127.0.0.1:8000/{custom_url}/"
        else:
            last = Accordance.objects.last()
            next_pk = (last.pk + 1) if last else 1
            short_url = f"http://127.0.0.1:8000/{next_pk}/"
        self.object.short_url = short_url
        self.object.save()
        return super().form_valid(form)


class AccordanceListView(ListView):
    """
    Представление для отображения списка ссылок
    """
    model = Accordance
    template_name = "bitlyapp/accordance_list.html"
    paginate_by = 100


class AccordanceRedirect(RedirectView):
    """
    Класс перенаправления на полную ссылку
    """
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Accordance, short_url="http://127.0.0.1:8000/" + kwargs["short_url"] + "/")
        return obj.full_url

unit_Avto/bitlyapp/templates/bitlyapp/accordance_form.html
{% extends "bitlyapp/base.html" %}

{% block title %}
    Create a link
{% endblock %}

{% block body %}
    <div class="fixed-container">
        <h1>Create a link</h1>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-lg">Create a link</button>
        </form>
    </div>
{% endblock %}

unit_Avto/bitlyapp/templates/bitlyapp/accordance_list.html
{% extends "bitlyapp/base.html" %}

{% block title %}
    List of links
{% endblock %}

{% block body %}
    <div class="fixed-container">
        <h1>List of links</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full url</th>
                <th scope="col">Short url</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td><a class="links" href='{{ object.full_url }}'>{{ object.full_url }}</a>
                    <td><a class="links" href='{{ object.short_url }}'>{{ object.short_url }}</a>
                </tr>

            {% endfor %}
            </tbody>
{% endblock %}

unit_Avto/bitlyapp/templates/bitlyapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
    <style>
        .fixed-container {
            max-width: 1000px;
            margin-left: auto;
            margin-right: auto;
        }

        .nav {
            margin: 10px 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .wide-input {
            width: 100%; /* Измените на желаемую ширину, например, 100% */
            max-width: 1000px; /* Ограничение максимальной ширины */
        }

        .links {
            text-decoration: none;
            color: black;
        }

        .nav > a {
            font-size: larger;
              }

    </style>
</head>
<body>
{% load static %}
<div class="fixed-container">
    <div class="nav">
        <a class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href={% url 'bitlyapp:accordance-create' %}>Create a link</a>
        <a class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href={% url 'bitlyapp:accordance-list' %}>List of links</a>
        <a class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href={% url 'bitlyapp:accordance' %}>API</a>
    </div>
</div>
{% block body %}
    Base body
{% endblock %}

{% block footer %}
    <footer>

    </footer>
{% endblock %}

</body>
</html>